// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6jyrt4lv-Py-Qe6suFJZ7jYx4rU8YEw',
    appId: '1:313090085620:web:a35280c267304f5e8504a1',
    messagingSenderId: '313090085620',
    projectId: 'dziennikkierowcy-ca3d2',
    authDomain: 'dziennikkierowcy-ca3d2.firebaseapp.com',
    storageBucket: 'dziennikkierowcy-ca3d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26VC5WW59qE6O-xOtXr4w3BBGccXWB94',
    appId: '1:313090085620:android:49ca111f9d1138018504a1',
    messagingSenderId: '313090085620',
    projectId: 'dziennikkierowcy-ca3d2',
    storageBucket: 'dziennikkierowcy-ca3d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRUrQJej-PNKTQwH6qrf4oaJ4uPrSTnJw',
    appId: '1:313090085620:ios:e6d7656eaf68e2778504a1',
    messagingSenderId: '313090085620',
    projectId: 'dziennikkierowcy-ca3d2',
    storageBucket: 'dziennikkierowcy-ca3d2.appspot.com',
    iosClientId: '313090085620-uhmal6f9nsjoi6hibt8lfgev3564fbtn.apps.googleusercontent.com',
    iosBundleId: 'com.szymonmatecki.dziennikKierowcy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRUrQJej-PNKTQwH6qrf4oaJ4uPrSTnJw',
    appId: '1:313090085620:ios:e6d7656eaf68e2778504a1',
    messagingSenderId: '313090085620',
    projectId: 'dziennikkierowcy-ca3d2',
    storageBucket: 'dziennikkierowcy-ca3d2.appspot.com',
    iosClientId: '313090085620-uhmal6f9nsjoi6hibt8lfgev3564fbtn.apps.googleusercontent.com',
    iosBundleId: 'com.szymonmatecki.dziennikKierowcy2',
  );
}
