// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KtIEA0IwfalSwlC9Nu8C1y0fvV1NYkc',
    appId: '1:664011785618:web:09485e0e63f51bf4076d4b',
    messagingSenderId: '664011785618',
    projectId: 'dziennikkierowcy2',
    authDomain: 'dziennikkierowcy2.firebaseapp.com',
    storageBucket: 'dziennikkierowcy2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjx3nSn3pqUM3zJAwXcMIjxg0uMrO8c1g',
    appId: '1:664011785618:android:32b35d37bd8e3960076d4b',
    messagingSenderId: '664011785618',
    projectId: 'dziennikkierowcy2',
    storageBucket: 'dziennikkierowcy2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_pzAmT33VE3DaeUPLxKxdR44ecbVW7Pg',
    appId: '1:664011785618:ios:752a4e8a9f7c4100076d4b',
    messagingSenderId: '664011785618',
    projectId: 'dziennikkierowcy2',
    storageBucket: 'dziennikkierowcy2.appspot.com',
    iosClientId: '664011785618-8ap05cg0b2m414fe7huan7m4gmge5651.apps.googleusercontent.com',
    iosBundleId: 'com.szymonmatecki.dziennikKierowcy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_pzAmT33VE3DaeUPLxKxdR44ecbVW7Pg',
    appId: '1:664011785618:ios:752a4e8a9f7c4100076d4b',
    messagingSenderId: '664011785618',
    projectId: 'dziennikkierowcy2',
    storageBucket: 'dziennikkierowcy2.appspot.com',
    iosClientId: '664011785618-8ap05cg0b2m414fe7huan7m4gmge5651.apps.googleusercontent.com',
    iosBundleId: 'com.szymonmatecki.dziennikKierowcy2',
  );
}
